### ISSUE TITLE
spdy support not present

### ISSUE THREAD

**Issue by rektide** [koajs/koala#16]
It was dropped in https://github.com/koajs/koala/commit/07ea52018d93b3206b504b606eb62aaac6bfb498 yet the docs still assert it is a thing.

**Comment by jonathanong** [comment]
I should revert that... That repo supports http2 now

**Comment by rektide** [comment]
It does. :)

**Comment by nickmccurdy** [comment]
We're dropping SPDY support, it's deprecated. See #48.
