### ISSUE TITLE
Support for koa 2.0.0

### ISSUE THREAD

**Issue by buzinas** [koajs/koala#17]

**Comment by nicolasmccurdy** [comment]
Is this in progress? Either way, I'd be happy to help if I can figure it out.

**Comment by richenlin** [comment]
I promise it's already in progress. And welcome to help us

**Comment by nfantone** [comment]
I can take this, if you guys want. I've done it before with some other Koa packages (like [koa-jwt](https://github.com/koajs/jwt/pull/40)). Let me know what you think.

**Comment by nickmccurdy** [comment]
Thanks! Do you want to tackle #30 with me first?

**Comment by nfantone** [comment]
Happy to do so :)

**Comment by nickmccurdy** [comment]
I forgot that I started a branch for this a while ago, it might be useful as a starting point. Right now it's just upgrading to Koa 2.0.0 and using class syntax, there are still generator deprecation warnings we would need to fix.

https://github.com/koajs/koala/compare/use-koa-2

@nfantone Would you like to join our [Gitter chat](https://gitter.im/koajs/koala)?

**Comment by doug-wade** [comment]
@jonathanong I'd like to publish this.  Could you grant me permissions or do it yourself?
