### ISSUE TITLE
Bluebird version 3 support

### ISSUE THREAD

**Issue by solsend2l** [koajs/koala#18]
http://bluebirdjs.com/docs/new-in-bluebird-3.html

**Comment by nickmccurdy** [comment]
Note sure if this is a duplicate of #34 now. Also, I think we should move to native Promises instead of updating Bluebird. Thoughts?

**Comment by nickmccurdy** [comment]
Nevermind, looks like we're already using Bluebird 3. Let me know if there are any issues with it.

**Comment by doug-wade** [comment]
@nickmccurdy I would definitely be in favor of removing bluebird in favor of native promises.
