### ISSUE TITLE
Remove bluebird

### ISSUE THREAD

**Issue by doug-wade** [koajs/koala#46]
In [this comment](https://github.com/koajs/koala/issues/18#issuecomment-326832305) @nickmccurdy suggested we remove Bluebird in favor of native promises.  While Bluebird has some nifty features that native promises lack, we should make the migration anyway, as native promises have a smaller footprint (don't need to be `npm install`ed), and have a more standard api.

**Comment by nickmccurdy** [comment]
Want me to pick this up? Another option is `any-promise`, though Node has supported Promise since `0.12` so I'm tempted to just use native Promises directly.

**Comment by nickmccurdy** [comment]
I just [removed bluebird from `package.json`](https://github.com/koajs/koala/commit/1089a6a7c8518cd0dfa926bf32477a7b30de138b). We actually weren't using it directly importing it anywhere, it was just being used by dependencies. I filed issues in those repositories.

```
~/Repos/koala → npm ls bluebird
koala@1.0.0 /Users/nick/Repos/koala
├─┬ koa-cash@2.1.1
│ └── bluebird@3.5.0 
├─┬ koa-error@2.1.0
│ └─┬ co-render@1.1.0
│   └─┬ consolidate@0.14.5
│     └── bluebird@3.5.0  deduped
└─┬ koa-file-server@2.3.1
  └─┬ spdy-push@1.0.2
    └── bluebird@2.11.0 
```
