### ISSUE TITLE
Use Jest instead of Mocha

### ISSUE THREAD

**Issue by nickmccurdy** [koajs/koala#52]
- Koa upstream has made the switch (while I personally prefer Jest, this is the main reason).
- Jest has more of a convention over configuration / batteries included approach vs. Mocha's more minimal and modular approach. However, the built in Jest APIs are simple and include common things like matchers and mocks. While we already have some of this set up, it could help us reduce maintenance on Mocha setup in the future.
- Built in coverage, personally I find it more reliable and convenient than istanbul (though we could alternatively switch to nyc).
- Seriously cool features like snapshots that are hard to find in other frameworks.
- Built in Babel support so you can watch tests while transpiling without having to set up another tool.
- Jest lets you put test files in the same directories as source files, making imports easier to maintain and test code easier to find an verify.

**Comment by nfantone** [comment]
Closed by #53.
