### ISSUE TITLE
Maintaining

### ISSUE THREAD

**Issue by lohfu** [koajs/koala#58]
Hi,

I am currently building some koa utilities and saw this project is seeking a maintainer. Is this still the case?

/ Linus

**Comment by doug-wade** [comment]
Hi @lohfu!  I'm back tinkering with koa after a break during the winter.  I have merge permissions, so if you'd like to contribute, I'd be happy for your help.  Top of mind for me currently is https://github.com/koajs/koala/issues/59, which will likely involve a change to [koa-trace](https://github.com/koajs/trace).  Any contributions are welcome!
